common:
  security:
    enabled: false
  feign-oauth:
    enabled: false
  mvc:
    enabled: false
server:
  ssl:
    enabled: false
  servlet:
    context-path: /badge-system
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 710370129096-1ds2ep35gng8urabd5imho90u2b31027.apps.googleusercontent.com
            client-secret: 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
  application:
    name: cs544-202403-project
  datasource:
    url: jdbc:mysql://localhost:3306/attendance_system_db
    password: SSjohn55Y$
    username: enyonathan
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  mail:
    host: smtp.gmail.com
    port: 587
    username: ahmed.elaked20@gmail.com
    password: "pnzd qcoj gvgc rsrz"  # Ensure to enclose the password in double quotes
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
  file:
    name: /CS544/Logging/${spring.application.name}/logs
